# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  
  # cache IDF tools folder
  - task: Cache@2
    displayName: Cache ESP32 tools
    inputs:
      key: 'esp32_tools | 4_3_1'
      restoreKeys: |
        esp32ToolsKey
      path: $(UserProfile)\.espressif\tools
      cacheHitVar: ESP32_TOOLS_CACHE_RESTORED

  # cache pip packages
  - task: Cache@2
    displayName: Cache pip packages
    inputs:
      key: 'python | "$(Agent.OS)" | esp-idf\requirements.txt'
      restoreKeys: | 
        python | "$(Agent.OS)"
        python
      path: $(PIP_CACHE_DIR)

  # Use Python Version 3.6 and add it to path
  - task: UsePythonVersion@0
    displayName: Set Python to v3.6
    inputs:
      versionSpec: '3.6' 
      addToPath: true

  # run IDF installers
  - task: PowerShell@2
    displayName: Install IDF stuff (step 1)
    inputs:
      targetType: 'filePath'
      filePath: $(Agent.BuildDirectory)\s\esp-idf\install.ps1
      workingDirectory: $(Agent.BuildDirectory)\s\esp-idf

  - task: PowerShell@2
    displayName: Install IDF stuff (step 2)
    inputs:
      targetType: 'inline'
      workingDirectory: $(Agent.BuildDirectory)\s\esp-idf
      script: |
        python -m pip install -r requirements.txt

  - task: PowerShell@2
    displayName: Install IDF stuff (step 3)
    inputs:
      targetType: 'filePath'
      filePath: $(Agent.BuildDirectory)\s\esp-idf\export.ps1
      workingDirectory: $(Agent.BuildDirectory)\s\esp-idf

  # need to add these to the PATH, in case the tools where restored from the cache
  - script: |
      echo "##vso[task.prependpath]$(UserProfile)\.espressif\tools\xtensa-esp32-elf\esp-2021r1-8.4.0\xtensa-esp32-elf\bin"
      echo "##vso[task.prependpath]$(UserProfile)\.espressif\tools\xtensa-esp32s2-elf\esp-2021r1-8.4.0\xtensa-esp32s2-elf\bin"
      echo "##vso[task.prependpath]$(UserProfile)\.espressif\tools\riscv32-esp-elf\esp-2021r1-8.4.0\riscv32-esp-elf\bin"
      echo "##vso[task.prependpath]$(UserProfile)\.espressif\tools\idf-exe\1.0.1"
    condition: ne(variables.ESP_TOOLS_CACHE_RESTORED, 'true')
    displayName: Add IDF tools to path

  - script: echo "##vso[task.prependpath]C:\Windows\System32"
    displayName: Tweak PATH to reach cmd
